# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.search_api import SearchApi  # noqa: E501
from openapi_client.rest import ApiException


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.search_api.SearchApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_search_get(self):
        """Test case for api_search_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
