# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.videostream_api import VideostreamApi  # noqa: E501
from openapi_client.rest import ApiException


class TestVideostreamApi(unittest.TestCase):
    """VideostreamApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.videostream_api.VideostreamApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_videostream_post(self):
        """Test case for api_videostream_post

        """
        pass

    def test_api_videostream_ul_token_body_post(self):
        """Test case for api_videostream_ul_token_body_post

        """
        pass

    def test_api_videostream_ul_token_post(self):
        """Test case for api_videostream_ul_token_post

        """
        pass

    def test_api_videostream_video_id_get(self):
        """Test case for api_videostream_video_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
