# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.courses_api import CoursesApi  # noqa: E501
from openapi_client.rest import ApiException


class TestCoursesApi(unittest.TestCase):
    """CoursesApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.courses_api.CoursesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_api_courses_course_id_add_session_post(self):
        """Test case for api_courses_course_id_add_session_post

        """
        pass

    def test_api_courses_create_course_post(self):
        """Test case for api_courses_create_course_post

        """
        pass

    def test_api_courses_get(self):
        """Test case for api_courses_get

        """
        pass

    def test_api_courses_id_get(self):
        """Test case for api_courses_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
