# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.add_session_model import AddSessionModel  # noqa: E501
from openapi_client.rest import ApiException


class TestAddSessionModel(unittest.TestCase):
    """AddSessionModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAddSessionModel(self):
        """Test AddSessionModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.add_session_model.AddSessionModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
