# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Enrollment(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'user': 'User',
        'course': 'Course',
        'enrollment_date_utc': 'datetime'
    }

    attribute_map = {
        'id': 'id',
        'user': 'user',
        'course': 'course',
        'enrollment_date_utc': 'enrollmentDateUtc'
    }

    def __init__(self, id=None, user=None, course=None, enrollment_date_utc=None):  # noqa: E501
        """Enrollment - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._user = None
        self._course = None
        self._enrollment_date_utc = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if user is not None:
            self.user = user
        if course is not None:
            self.course = course
        if enrollment_date_utc is not None:
            self.enrollment_date_utc = enrollment_date_utc

    @property
    def id(self):
        """Gets the id of this Enrollment.  # noqa: E501


        :return: The id of this Enrollment.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Enrollment.


        :param id: The id of this Enrollment.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def user(self):
        """Gets the user of this Enrollment.  # noqa: E501


        :return: The user of this Enrollment.  # noqa: E501
        :rtype: User
        """
        return self._user

    @user.setter
    def user(self, user):
        """Sets the user of this Enrollment.


        :param user: The user of this Enrollment.  # noqa: E501
        :type: User
        """

        self._user = user

    @property
    def course(self):
        """Gets the course of this Enrollment.  # noqa: E501


        :return: The course of this Enrollment.  # noqa: E501
        :rtype: Course
        """
        return self._course

    @course.setter
    def course(self, course):
        """Sets the course of this Enrollment.


        :param course: The course of this Enrollment.  # noqa: E501
        :type: Course
        """

        self._course = course

    @property
    def enrollment_date_utc(self):
        """Gets the enrollment_date_utc of this Enrollment.  # noqa: E501


        :return: The enrollment_date_utc of this Enrollment.  # noqa: E501
        :rtype: datetime
        """
        return self._enrollment_date_utc

    @enrollment_date_utc.setter
    def enrollment_date_utc(self, enrollment_date_utc):
        """Sets the enrollment_date_utc of this Enrollment.


        :param enrollment_date_utc: The enrollment_date_utc of this Enrollment.  # noqa: E501
        :type: datetime
        """

        self._enrollment_date_utc = enrollment_date_utc

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Enrollment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
