# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Room(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'webuntis_id': 'int',
        'name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'webuntis_id': 'webuntisId',
        'name': 'name'
    }

    def __init__(self, id=None, webuntis_id=None, name=None):  # noqa: E501
        """Room - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._webuntis_id = None
        self._name = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.webuntis_id = webuntis_id
        self.name = name

    @property
    def id(self):
        """Gets the id of this Room.  # noqa: E501


        :return: The id of this Room.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Room.


        :param id: The id of this Room.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def webuntis_id(self):
        """Gets the webuntis_id of this Room.  # noqa: E501


        :return: The webuntis_id of this Room.  # noqa: E501
        :rtype: int
        """
        return self._webuntis_id

    @webuntis_id.setter
    def webuntis_id(self, webuntis_id):
        """Sets the webuntis_id of this Room.


        :param webuntis_id: The webuntis_id of this Room.  # noqa: E501
        :type: int
        """
        if webuntis_id is None:
            raise ValueError("Invalid value for `webuntis_id`, must not be `None`")  # noqa: E501

        self._webuntis_id = webuntis_id

    @property
    def name(self):
        """Gets the name of this Room.  # noqa: E501


        :return: The name of this Room.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Room.


        :param name: The name of this Room.  # noqa: E501
        :type: str
        """

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Room):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
