# coding: utf-8

"""
    vc_webapi

    Web API for the Virtual Classroom project  # noqa: E501

    The version of the OpenAPI document: v1
    Contact: 237294@via.dk
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ScheduledSession(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'int',
        'webuntis_id': 'int',
        'webuntis_course_id': 'int',
        'course_id': 'int',
        'course': 'Course',
        'room_id': 'int',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'webuntis_teacher_ids': 'list[int]'
    }

    attribute_map = {
        'id': 'id',
        'webuntis_id': 'webuntisId',
        'webuntis_course_id': 'webuntisCourseId',
        'course_id': 'courseId',
        'course': 'course',
        'room_id': 'roomId',
        'start_time': 'startTime',
        'end_time': 'endTime',
        'webuntis_teacher_ids': 'webuntisTeacherIds'
    }

    def __init__(self, id=None, webuntis_id=None, webuntis_course_id=None, course_id=None, course=None, room_id=None, start_time=None, end_time=None, webuntis_teacher_ids=None):  # noqa: E501
        """ScheduledSession - a model defined in OpenAPI"""  # noqa: E501

        self._id = None
        self._webuntis_id = None
        self._webuntis_course_id = None
        self._course_id = None
        self._course = None
        self._room_id = None
        self._start_time = None
        self._end_time = None
        self._webuntis_teacher_ids = None
        self.discriminator = None

        if id is not None:
            self.id = id
        self.webuntis_id = webuntis_id
        self.webuntis_course_id = webuntis_course_id
        if course_id is not None:
            self.course_id = course_id
        if course is not None:
            self.course = course
        self.room_id = room_id
        self.start_time = start_time
        self.end_time = end_time
        self.webuntis_teacher_ids = webuntis_teacher_ids

    @property
    def id(self):
        """Gets the id of this ScheduledSession.  # noqa: E501


        :return: The id of this ScheduledSession.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ScheduledSession.


        :param id: The id of this ScheduledSession.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def webuntis_id(self):
        """Gets the webuntis_id of this ScheduledSession.  # noqa: E501


        :return: The webuntis_id of this ScheduledSession.  # noqa: E501
        :rtype: int
        """
        return self._webuntis_id

    @webuntis_id.setter
    def webuntis_id(self, webuntis_id):
        """Sets the webuntis_id of this ScheduledSession.


        :param webuntis_id: The webuntis_id of this ScheduledSession.  # noqa: E501
        :type: int
        """
        if webuntis_id is None:
            raise ValueError("Invalid value for `webuntis_id`, must not be `None`")  # noqa: E501
        if webuntis_id is not None and webuntis_id < 1:  # noqa: E501
            raise ValueError("Invalid value for `webuntis_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._webuntis_id = webuntis_id

    @property
    def webuntis_course_id(self):
        """Gets the webuntis_course_id of this ScheduledSession.  # noqa: E501


        :return: The webuntis_course_id of this ScheduledSession.  # noqa: E501
        :rtype: int
        """
        return self._webuntis_course_id

    @webuntis_course_id.setter
    def webuntis_course_id(self, webuntis_course_id):
        """Sets the webuntis_course_id of this ScheduledSession.


        :param webuntis_course_id: The webuntis_course_id of this ScheduledSession.  # noqa: E501
        :type: int
        """
        if webuntis_course_id is None:
            raise ValueError("Invalid value for `webuntis_course_id`, must not be `None`")  # noqa: E501
        if webuntis_course_id is not None and webuntis_course_id < 1:  # noqa: E501
            raise ValueError("Invalid value for `webuntis_course_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._webuntis_course_id = webuntis_course_id

    @property
    def course_id(self):
        """Gets the course_id of this ScheduledSession.  # noqa: E501


        :return: The course_id of this ScheduledSession.  # noqa: E501
        :rtype: int
        """
        return self._course_id

    @course_id.setter
    def course_id(self, course_id):
        """Sets the course_id of this ScheduledSession.


        :param course_id: The course_id of this ScheduledSession.  # noqa: E501
        :type: int
        """

        self._course_id = course_id

    @property
    def course(self):
        """Gets the course of this ScheduledSession.  # noqa: E501


        :return: The course of this ScheduledSession.  # noqa: E501
        :rtype: Course
        """
        return self._course

    @course.setter
    def course(self, course):
        """Sets the course of this ScheduledSession.


        :param course: The course of this ScheduledSession.  # noqa: E501
        :type: Course
        """

        self._course = course

    @property
    def room_id(self):
        """Gets the room_id of this ScheduledSession.  # noqa: E501


        :return: The room_id of this ScheduledSession.  # noqa: E501
        :rtype: int
        """
        return self._room_id

    @room_id.setter
    def room_id(self, room_id):
        """Sets the room_id of this ScheduledSession.


        :param room_id: The room_id of this ScheduledSession.  # noqa: E501
        :type: int
        """
        if room_id is None:
            raise ValueError("Invalid value for `room_id`, must not be `None`")  # noqa: E501
        if room_id is not None and room_id < 1:  # noqa: E501
            raise ValueError("Invalid value for `room_id`, must be a value greater than or equal to `1`")  # noqa: E501

        self._room_id = room_id

    @property
    def start_time(self):
        """Gets the start_time of this ScheduledSession.  # noqa: E501


        :return: The start_time of this ScheduledSession.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ScheduledSession.


        :param start_time: The start_time of this ScheduledSession.  # noqa: E501
        :type: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this ScheduledSession.  # noqa: E501


        :return: The end_time of this ScheduledSession.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this ScheduledSession.


        :param end_time: The end_time of this ScheduledSession.  # noqa: E501
        :type: datetime
        """
        if end_time is None:
            raise ValueError("Invalid value for `end_time`, must not be `None`")  # noqa: E501

        self._end_time = end_time

    @property
    def webuntis_teacher_ids(self):
        """Gets the webuntis_teacher_ids of this ScheduledSession.  # noqa: E501


        :return: The webuntis_teacher_ids of this ScheduledSession.  # noqa: E501
        :rtype: list[int]
        """
        return self._webuntis_teacher_ids

    @webuntis_teacher_ids.setter
    def webuntis_teacher_ids(self, webuntis_teacher_ids):
        """Sets the webuntis_teacher_ids of this ScheduledSession.


        :param webuntis_teacher_ids: The webuntis_teacher_ids of this ScheduledSession.  # noqa: E501
        :type: list[int]
        """

        self._webuntis_teacher_ids = webuntis_teacher_ids

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ScheduledSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
